### ISSUE TITLE
Hace falta una base de datos para el ejercicio

### ISSUE THREAD

**Issue by Pantuflip** [datasketch/meetupR#1]
Falta subir en la carpeta data el archivo de la base de datos "data/data_meetup_congreso.csv"

**Comment by CamilaAchuri** [comment]
Hola, @Pantuflip tienes razón, ya subí la base que es.

**Comment by CamilaAchury** [comment]
> Falta subir en la carpeta data el archivo de la base de datos "data/data_meetup_congreso.csv"

**Comment by CamilaAchury** [comment]
> Falta subir en la carpeta data el archivo de la base de datos "data/data_meetup_congreso.csv"
